### ISSUE TITLE
Imports 

### ISSUE THREAD

**Issue by kbrown** [devlato/react-easter#3]
Should work with React version > 15 <= 17.x ideally

**Comment by kbrown** [comment]
Unfortunately I'm getting test failures on my fork after attempting to upgrade

 FAIL  test/Component.js (6.43 s)
  <EasterEgg />
    ✓ Should render (35 ms)
    ✕ Should handle keys sequently without timeout (5031 ms)
    ✕ Should handle keys sequently with timeout (4 ms)

  ● <EasterEgg /> › Should handle keys sequently without timeout

    : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:

      70 | 
      71 | 
    > 72 |   it('Should handle keys sequently without timeout', function() {
         |   ^
      73 |     var child = createChild();
      74 |     var created = createComponent({
      75 |       keys: ['t', 'e', 's', 't']

      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (test/Component.js:72:3)
      at Object.<anonymous> (test/Component.js:45:1)
